### ISSUE TITLE
Add contributing guide

### ISSUE THREAD

**Issue by diegobernardes** [diegobernardes/flare#69]
Take this ones as example:

- https://github.com/alibaba/pouch/blob/master/CONTRIBUTING.md
- https://github.com/go-chi/chi/blob/master/CONTRIBUTING.md
- https://github.com/containous/traefik/blob/master/CONTRIBUTING.md
- https://github.com/GoogleCloudPlatform/container-diff
- https://github.com/GoogleCloudPlatform/container-diff/blob/master/CONTRIBUTING.md

**Comment by afgoulart** [comment]
Add require Docker
